import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),

  route("trading", "routes/trading.tsx"),
  route("trading/otc", "routes/trading.otc.tsx"),
  route("trading/stablecoin-access", "routes/trading.stablecoin-access.tsx"),
  route("asset-management", "routes/asset-management.tsx"),
  route("asset-management/portfolio", "routes/asset-management.portfolio.tsx"),
  route("asset-management/investment-advisory", "routes/asset-management.investment-advisory.tsx"),
  route("asset-management/license-regulation", "routes/asset-management.license-regulation.tsx"),
  route("whoweserve", "routes/whoweserve.tsx"),
  route("whoweserve/fintechs", "routes/whoweserve.fintechs.tsx"),
  route("whoweserve/corporates", "routes/whoweserve.corporates.tsx"),
  route("whoweserve/traders", "routes/whoweserve.traders.tsx"),
  route("whoweserve/institutions", "routes/whoweserve.institutions.tsx"),
  route("whoweserve/investors", "routes/whoweserve.investors.tsx"),
  route("custody", "routes/whoweserve.custody.tsx"),
  route("custody/mpcvaults", "routes/custody.mpvvaults.tsx"),
  route("custody/staking", "routes/custody.staking.tsx"),
  route("custody/KYCAML", "routes/custody.kycaml.tsx"),
  route("company-about", "routes/company.about.tsx"),
  route("resources", "routes/resources.tsx"),
  route("resources/apidocumentation", "routes/resources.apidocumentation.tsx"),
  route("company/careers", "routes/company.careers.tsx"),
  route("company/contact", "routes/company.contact.tsx"),
  route("dev/components", "routes/dev.components.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("cookies", "routes/cookies.tsx"),
  route("resources/casestudies", "routes/resources.casestudies.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
